name: Lint

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup poetry
        run: pipx install poetry

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install

      - name: Check poetry
        run: make lint-poetry

      - name: Check flake8
        run: make lint-flake8

      - name: Check mypy
        run: make lint-mypy

      - name: Check bandit
        run: make lint-bandit
